name: flutter_boiler_plate
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # For internalization.
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0 # library for internalization
  shared_preferences: ^2.0.5 # For storing data in local storage.
  flutter_mobx: ^2.0.0 # for state management and this provides the Observer.
  provider: ^5.0.0 # for state management
  mobx: ^2.0.1 # provides Store
  dio: ^4.0.0 # for APIs calling.
  connectivity: ^3.0.3 # for internet connection check
  shimmer: ^2.0.0 # for shimmer loading
  google_sign_in: '^4.5.1'
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  sms_otp_auto_verify: ^2.1.0
  sms_autofill: ^2.2.0
  firebase_database: ^9.0.12
  url_launcher: ^6.1.2
  file_picker: ^4.5.1
  firebase_storage: ^10.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2 #provides a concrete way of generating files using Dart code, outside of tools
  mobx_codegen: ^2.0.1+3 #for auto generating code for stores.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/demo.png
    - assets/image/google.png
    - assets/image/student_red.png
    - assets/image/holiday.png
    - assets/image/getmoney.png
    - assets/image/form.png
    - assets/image/complaint.png
    - assets/image/discuss.png
    - assets/image/faq.png
    - assets/image/feedbac.png
    - assets/image/feedback.png

  fonts:
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        style: normal
      - asset: assets/fonts/Inter-Medium.ttf
        style: normal
        weight: 500
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 600


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
